# Generated by Django 4.2.2 on 2023-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
